# This workflows will upload a Python Package using Twine when the 
# VERSION file is updated

name: Build

on: 
  push:
    branches:
    - master
    paths:
    - 'VERSION'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build distributions
      run: |
        python setup.py sdist --formats=gztar bdist_wheel --universal
    - name: Upload distributions
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
