# Build workflow does the following:
#   - checkout all files
#   - get the latest version number
#   - setup python 3.x env
#   - install python dependencies
#   - build python distributions
#   - create a tag and release
#   - upload assets to the release
#   - upload assets to pypi

name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_test_deploy:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set python path
      id: path
      run: echo "::set-output name=pythonv::c:/38/python"

    - name: Install dependencies
      run: |
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade pip
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade jsonpath-ng
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade pyyaml
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade pytest
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade setuptools
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade wheel
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade twine
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade requests

    - name: Build distributions
      run: |
        ${{steps.path.outputs.pythonv}} setup.py sdist --formats=gztar bdist_wheel --universal

    - name: Instal
      run: |
        ${{steps.path.outputs.pythonv}} setup.py install

    - name: Run tests
      run: |
        ${{steps.path.outputs.pythonv}} -m pytest --api_server=10.36.66.49 --api_server_port=11009 -s tests/test_clear_config.py

    - name: Get all changes
      id: file_changes
      uses: trilom/file-changes-action@v1.2.3

    - name: Output changed files
      id: changed_files
      run: echo ${{steps.file_changes.outputs.files_modified}}

    - name: Get VERSION number
      id: get_version
      if: true == contains(steps.file_changes.outputs.files_modified, 'VERSION')
      run: echo "::set-output name=version::$(cat VERSION)"

    - name: Create Release
      id: create_release
      if: true == contains(steps.file_changes.outputs.files_modified, 'VERSION')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Assets To Release
      if: true == contains(steps.file_changes.outputs.files_modified, 'VERSION')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: v${{ steps.get_version.outputs.version }}
        overwrite: true
        file_glob: true   
        
    - name: Upload Assets to Pypi
      if: true == contains(steps.file_changes.outputs.files_modified, 'VERSION')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        c:/38/Scripts/twine upload dist/*
