# Build workflow does the following:
#   - checkout all files
#   - get the latest version number
#   - setup python 3.x env
#   - install python dependencies
#   - build python distributions
#   - create a tag and release
#   - upload assets to the release
#   - upload assets to pypi

name: Build

on: [pull_request, workflow_dispatch]

jobs:
  build_test_deploy:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: set python path
      id: path
      run: echo "::set-output name=pythonv::c:/38/python"

    - name: Install dependencies
      run: |
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade pip
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade jsonpath-ng
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade pyyaml
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade pytest
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade setuptools
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade wheel
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade twine
        ${{steps.path.outputs.pythonv}} -m pip install --user --upgrade requests

    - name: Build distributions
      run: |
        ${{steps.path.outputs.pythonv}} setup.py sdist --formats=gztar bdist_wheel --universal

    - name: Get VERSION number
      id: get_version
      run: echo "::set-output name=version::$(cat VERSION)"
    
    - name: Test whl distribution installation
      run: |
        ${{steps.path.outputs.pythonv}} -m pip install dist/ixnetwork_open_traffic_generator-${{ steps.get_version.outputs.version }}-py2.py3-none-any.whl

    - name: Get all changes
      if: github.event_name == 'push'
      id: file_changes
      uses: jitterbit/get-changed-files@v1
      with:
          format: 'json'

    - name: Output changed files
      id: changed_files
      run: echo ${{steps.file_changes.outputs.modified}}

    - name: Create Release
      if: true == contains(steps.file_changes.outputs.modified, 'VERSION')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Assets To Release
      if: true == contains(steps.file_changes.outputs.modified, 'VERSION')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: v${{ steps.get_version.outputs.version }}
        overwrite: true
        file_glob: true   
        
    - name: Upload Assets to Pypi
      if: true == contains(steps.file_changes.outputs.modified, 'VERSION')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        "c:/38/Scripts/twine" upload dist/ixnetwork_open_traffic_generator-${{ steps.get_version.outputs.version }}-py2.py3-none-any.whl
        "c:/38/Scripts/twine" upload dist/ixnetwork_open_traffic_generator-${{ steps.get_version.outputs.version }}.tar
